import Head from "next/head";
import HomeBanner from "../components/HomeBanner";
import SectionHeading from "../components/SectionHeading";
import SingleProductCard from "../components/SingleProductCard";
import SingleCollection from "../components/SingleCollection";
import {
  customQuery,
  fetchMethod,
  fetchQuery,
  getAllCollections,
  getCollectionByHandle,
} from "../utils/operations";

export default function Home({ bestSeller, featureCollections }) {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomeBanner />
      {bestSeller !== null ? (
        <div>
          <SectionHeading hashTag="#MoreThanJewelry">
            Best Sellers
          </SectionHeading>
          <div className="grid grid-cols-3 gap-12 mt-16">
            <SingleProductCard
              title={bestSeller.products[0].title}
              price={bestSeller.products[0].variants[0].price}
              imgSrc={bestSeller.products[0].images[0].src}
              handle={bestSeller.products[0].handle}
            />
            <SingleProductCard
              title={bestSeller.products[1].title}
              price={bestSeller.products[1].variants[0].price}
              imgSrc={bestSeller.products[1].images[0].src}
              handle={bestSeller.products[1].handle}
            />
            <SingleProductCard
              title={bestSeller.products[2].title}
              price={bestSeller.products[2].variants[0].price}
              imgSrc={bestSeller.products[2].images[0].src}
              handle={bestSeller.products[2].handle}
            />
          </div>
        </div>
      ) : (
        ""
      )}

      {featureCollections !== null ? (
        <div className="my-32">
          <h1 className="text-center uppercase text-3xl font-semibold mb-12">
            Featured Collections
          </h1>
          <div className="grid grid-cols-2 gap-12">
            <SingleCollection
              name={featureCollections[0].title}
              description={featureCollections[0].description}
              imgSrc={featureCollections[0].image?.src || "/default2.jpg"}
              link={featureCollections[0].handle}
            />
            <SingleCollection
              name={featureCollections[1].title}
              description={featureCollections[1].description}
              imgSrc={featureCollections[1].image?.src || "/default2.jpg"}
              link={featureCollections[1].handle}
            />
          </div>
        </div>
      ) : (
        ""
      )}
    </div>
  );
}

export const getServerSideProps = async (context) => {
  const bestSeller = await getCollectionByHandle("the-bulletproof-collection");
  const featureCollections = await getAllCollections();

  return {
    props: {
      bestSeller,
      featureCollections,
    },
  };
};
