import Head from "next/head";
import {
  customQuery,
  fetchMethod,
  fetchQuery,
  getAllCollections,
} from "../utils/operations";

export default function Home({ collections, query }) {
  console.log({ collections, query });
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      Home page
    </div>
  );
}

export const getServerSideProps = async (context) => {
  const collections = await fetchMethod(3);

  return {
    props: {
      collections,
      query: context.query,
    },
  };
};
